apiVersion: v1
kind: Namespace
metadata:
  name: kube-mutual-tls-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: kube-mutual-tls-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: kube-mutual-tls-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccount: app
      containers:
      - name: app
        image: amitsaha/kube-mutual-tls-demo:insecure  
        env:
        - name: LISTEN_ADDR
          value: ":8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: kube-mutual-tls-demo
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080
